services:
  # this service should use the web image after you build it
  nextjs:
    build:
      context: .
    ports:
      - 3000:3000
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
  # nginx:
  #   image: nginx
  #   volumes:
  #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   - /etc/letsencrypt/live/zamanfu.fun/fullchain.pem:/etc/nginx/ssl/fullchain.pem
  #   - /etc/letsencrypt/live/zamanfu.fun/privkey.pem:/etc/nginx/ssl/privkey.pem
  #   ports:
  #   - "3000:3000"
  #   depends_on:
  #     - nextjs
  # this service is the database service using mongo from docker hub
  # mongo:
  #   image: mongo-replica:latest
  #   restart: always
  #   ports:
  #     - "27027:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password