networks:
    my-blog_network:

services:
  # this service should use the web image after you build it
  nextjs:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    # network_mode: host
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - my-blog_network
  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
    - /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - nextjs
    networks:
      - my-blog_network
  # this service is the database service using mongo from docker hub
  # mongo:
  #   image: mongo-replica:latest
  #   restart: always
  #   ports:
  #     - "27027:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password